version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./todo-backend
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: todo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    depends_on:
      - mysql

  frontend:
    build: ./todo-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
